### ISSUE TITLE
Dynamic column

### ISSUE THREAD

**Issue by jchapelle** [guigrpa/docx-templates#167] opened 2020-11-13 18:23 UTC
Hello,

Your lib is great.
I've been rendering tables in few minutes.

Would it be possible to render column dynamically ?
The use case is : my users would be able to select the data they want on a report and the app would render the column related to the user selection.

**Comment by jjhbw** [comment] 2020-11-16 06:50
Duplicate of #15

**Closed by jjhbw** 2020-11-16 06:50 UTC
