### ISSUE TITLE
 **bug** Show defined variables as it is if it is not defined in the data object

### ISSUE THREAD

**Issue by PreemyJoshy123** [guigrpa/docx-templates#285] opened 2022-10-11 10:00 UTC
![image](https://user-images.githubusercontent.com/115543202/195060447-e4a11f3d-4ca6-4760-b854-32f0983c48fd.png)

**Comment by mathe42** [comment] 2022-10-11 12:08
@PreemyJoshy123 Please provide a full reproduction with code + template! A simple image of the output log has no use to reproduce the problem.

**Comment by PreemyJoshy123** [comment] 2022-10-11 12:17
@mathe42  The below is the create report function and the template i am using to replace variables.Here i am not assigning value to variable data .But after creating report in need to retain that ${data} as it is . How it is possible .

const buffer1 = await createReport({
      template: content,
      cmdDelimiter: ['${', '}'],
      data: {
		firstname:'jhon',
		employeename:'jhon smith'
		},
    });
![template](https://user-images.githubusercontent.com/115543202/195086931-32863380-67b8-4ac0-a49c-5aa237d1abc9.png)

**Comment by mathe42** [comment] 2022-10-11 12:19
That is not possible... You could use 

```ts
const data = {...}
data.data = data

createReport{{..., data})
```

**Comment by PreemyJoshy123** [comment] 2022-10-11 12:24
we can't asume that ${data} will be always that it will change according to each user . i m using this for creating letters for the employees in my project . If we mention any variable that is not defined in data object we need to show that variable as it is . How it is possible ??

**Comment by mathe42** [comment] 2022-10-11 12:29
You could do ${ myVar ?? 'fallback'} 

Not sure what you want to accive can you give some examples?

**Comment by mathe42** [comment] 2022-10-11 12:41
What about:

`${ myVar ?? '${myVar}'}` in template?

**Comment by PreemyJoshy123** [comment] 2022-10-13 06:21
@mathe42  Can you show me an example for error handler to catch errors in template commands .

**Comment by jjhbw** [comment] 2022-10-13 10:03
@PreemyJoshy123 
https://github.com/guigrpa/docx-templates#custom-error-handler

Closing this issue because it is not a bug.

**Closed by jjhbw** 2022-10-13 10:03 UTC
