### ISSUE TITLE
LINK inside FOR throwing 'INTERNAL_ERROR' in v4.1.1

### ISSUE THREAD

**Issue by chelbighofrane** [guigrpa/docx-templates#133] opened 2020-06-08 13:06 UTC
Unfortunately the error still occurs in version 4.1.1

**Comment by jjhbw** [comment] 2020-06-08 13:25
Hmmm, thats weird. Do you have a minimal repro case? Including the template please.

I already tried to reproduce this in https://github.com/guigrpa/docx-templates/issues/83, and I made a regression test for this. The template that this test uses is https://github.com/guigrpa/docx-templates/blob/master/src/__tests__/fixtures/link-regression-issue-83.docx

**Comment by chelbighofrane** [comment] 2020-06-08 13:54
This is the template: [temp.docx](https://github.com/guigrpa/docx-templates/files/4746312/temp.docx)
the code: 
[code.txt](https://github.com/guigrpa/docx-templates/files/4746342/code.txt)
and this is the error I get : 
[error.txt](https://github.com/guigrpa/docx-templates/files/4746359/error.txt)

**Comment by jjhbw** [comment] 2020-06-08 14:46
Thanks.

When opening your template (`temp.docx`), Word 2016 uses Compatibility Mode. This suggests that the file is corrupt or otherwise broken. Which version of Word did you use to build the template? Please ensure you are running the latest version of your MS Word product (with all the latest patches).

I tried to build a reproduction case by copying the text contents of your template into a new Word file, see 02271fe68ab1a0fa5944345a4035bb9d822e3287. Weirdly, this test passes without a problem...

Any ideas what the cause might be?

**Comment by chelbighofrane** [comment] 2020-06-08 19:30
I was using 2010 version and also I tried with 2016 and still having the same error. Weird! cause other features(html,images,loop,conditions,link outside loops ...) are working as expected except links in loop. :/

**Comment by DvirH** [comment] 2020-08-26 11:31
It happens to me as well. Im using most recent office version. I found work around using the +++HTML tag to add <a>

**Comment by jjhbw** [comment] 2020-08-26 11:48
@DvirH can you post a reproduction case with a template and some code?
Also please make sure you're running the latest version of the library.

**Comment by DvirH** [comment] 2020-08-26 13:18
https://github.com/DvirH/reproduce_links

**Comment by jjhbw** [comment] 2020-09-08 11:53
@DvirH @chelbighofrane Thanks for your examples!

After a bit of experimentation, it seems that the `INTERNAL ERROR` only happens when the `LINK` command is formatted somehow (e.g. bold or underlined). See example template in 9b9d84c2e4ad6608e881b49d05ca3d9e57034a72.

I'll try and get a fix in, but note that the affected code is pretty deep in the lib and fully grasping what goes wrong may take a while.

**Comment by jjhbw** [comment] 2020-09-08 11:59
A short term fix/hack would be to remove all formatting from the affected LINK command in your template.

**Comment by jjhbw** [comment] 2020-09-08 13:19
@guigrpa can you maybe give me a pointer here? I stared at this code for a while, but I couldn't find what's going wrong here.

The `INTERNAL ERROR` is thrown here:
https://github.com/guigrpa/docx-templates/blob/ddeb00b1781c070e3e006e401a34912bf6c8081b/src/processTemplate.ts#L326-L329

 I have confirmed that this error occurs when LINK commands are formatted (e.g. bold/underlined) **and** placed within a FOR loop (see example template here https://github.com/guigrpa/docx-templates/commit/9b9d84c2e4ad6608e881b49d05ca3d9e57034a72)

Would be great if you could point me in the right direction!

**Comment by guigrpa** [comment] 2020-09-10 11:02
Hmm, it looks like the input and output trees have gotten out of sync. When the next move is to the `SIDE`, the code first moves the output node pointer up the tree one level, so that a child can be created next as a sibling to the previous node. The code throws because `nodeOut` has no parent, so the question is: where is it pointing to? Maybe it was moved incorrectly in the previous step?

Since you mention that it happens only within a loop, maybe `nodeOut` was incorrectly updated at the end of an iteration?

I think it would pay to execute it step by step, watching input and output pointers as they move…

**Comment by jjhbw** [comment] 2021-07-12 07:38
Fix released in v4.7.0. Should be on NPM shortly. Let me know if you encounter any weirdness!

**Closed by jjhbw** 2021-07-12 07:38 UTC
Labels: bug
