### ISSUE TITLE
Nested table not rendering

### ISSUE THREAD

**Issue by drinac** [guigrpa/docx-templates#277] opened 2022-05-31 14:56 UTC
When nesting a table with FOR loop inside a table row that is also rendered with a FOR loop, the whole nested table is not rendered.
When the nested loop is not repeating nested table rows, the values are rendered, as in the second table inside example.

Example :
[nested_table.docx](https://github.com/guigrpa/docx-templates/files/8806148/nested_table.docx)
![template_example](https://user-images.githubusercontent.com/2254498/171204351-bdf9fbdd-f471-4b1a-90c0-8bf93b3aa825.jpg)

Result:
![table_not_rendered](https://user-images.githubusercontent.com/2254498/171202816-7573632a-3cac-477e-b16f-dcab6a7bfaa5.jpg)
Expected result:
![table_expected](https://user-images.githubusercontent.com/2254498/171203135-a06f9066-3705-4817-a3b8-ad18cdf664ee.jpg)

-Environment:
Nodejs v15.11.0
docx-temlates@4.9.2

**Comment by jjhbw** [comment] 2022-06-13 12:56
I'm afraid this is a duplicate of https://github.com/guigrpa/docx-templates/issues/82. Sorry for the disappointing answer. Note my final comment in that issue for potential workarounds.

**Closed by jjhbw** 2022-06-13 12:56 UTC
Labels: triage
