### ISSUE TITLE
LINK inside FOR throwing 'INTERNAL_ERROR' in v3.1.1

### ISSUE THREAD

**Issue by piemasters** [guigrpa/docx-templates#83] opened 2019-08-28 08:26 UTC
Links were working fine (although without styling) in v3.0.0. I spotted you fixed the styling issue in 3.1.1 (thanks!) so I upgraded. Unfortunately I'm now getting an error from line 350 in processTempalate.js.

After a bit of debugging I've found that links are fine outside of FOR loops but throw the error when placed inside them. The link doesn't have to reference the FOR to cause the error, 
`+++LINK ({ url: 'http://www.test.com', label: 'Link' })+++ `
for example still causes the error to be thrown.

Thanks again for creating and maintaining this!

**Comment by piemasters** [comment] 2019-08-28 08:46
After looking through the code a bit more it seems like its being triggered on line 429: 
`'ctx.textRunPropsNode = nodeIn;'`
Removing it fixes the error being thrown, but breaks the styling.

**Comment by Suley** [comment] 2020-04-13 12:44
please fix it.

**Comment by jjhbw** [comment] 2020-04-13 16:47
@Suley @piemasters i've built a test case for this in #108 

I could not reproduce the error on the 4.0.0 release candidate. Can you verify that the test document I included in #108 contains the error case you mentioned?

If the test document resembles the one that errors out, then I guess the next major release will solve this issue. We'll release 4.0.0 soon. I'll leave the regression test case in.

**Comment by Suley** [comment] 2020-04-14 02:14
@jjhbw Thanks. Really appreciate your hard working. I will try it later!

**Comment by jjhbw** [comment] 2020-04-14 08:29
If the test in PR #108 correctly covers the case (let me know if it doesn't!) then I think this bug has been fixed with yesterday's 4.0.0 release. Let me know if it still occurs! I'll merge the regression test just to be sure.

**Closed by jjhbw** 2020-04-14 08:29 UTC
Labels: bug
