### ISSUE TITLE
HTML causing unreadable content error message

### ISSUE THREAD

**Issue by JoshuaTruscott** [guigrpa/docx-templates#222] opened 2021-07-10 14:29 UTC
When a HTML command is present in a template, opening the output document results in message: 
"Word found unreadable content in "template.docx". Do you want to recover the contents of this document? If you trust the source of this document, click Yes."

Tested using the HTML example from the README

Example:
```
const buffer = await createReport({
  template: fs.readFileSync("template.docx")
});
fs.writeFileSync("output.docx", buffer);
```

[Template used](https://filebin.net/wunx3ucprhhx07nj/template.docx)

Environment:
docx-templates v4.6.4
Node v14.2.0
Mac OS X v11.4

Thank you

**Comment by jjhbw** [comment] 2021-07-10 14:39
This probably means your specific HTML is malformed. Please provide a reproducible example, ideally limited to the HTML command in question.

**Comment by JoshuaTruscott** [comment] 2021-07-10 21:29
No problem, I've added the snippet and template used

**Comment by jjhbw** [comment] 2021-07-11 09:29
Got it. Thanks for reporting. Looks like I messed something up when fixing #217 . This should be working as intended again after 636db40f1f7a8cbb1d8f303d0f59fd69641ee837, which is currently on master and will be in the next release.

**Closed by jjhbw** 2021-07-11 09:29 UTC
Labels: bug

**Comment by JoshuaTruscott** [comment] 2021-07-11 12:41
Amazing, thanks for all your help!

**Comment by jjhbw** [comment] 2021-07-12 07:38
Fix released in v4.7.0. Should be on NPM shortly.

**Comment by gognjanovski** [comment] 2023-03-05 18:46
I get the same error when I try to inject more then 2 images with html.

```
<meta charset="UTF-8">
<body>
    <div style="margin-top: 20px;">
        <img width="30" height="30"
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Circle-withsegments.svg/1200px-Circle-withsegments.svg.png" />
        <img width="30" height="30"
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Circle-withsegments.svg/1200px-Circle-withsegments.svg.png" />
        <img width="30" height="30"
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Circle-withsegments.svg/1200px-Circle-withsegments.svg.png" />
    </div>
</body>
```

Environment:
docx-templates v4.11.0
Node v14.17.3
Mac OS X v13.1

**Comment by jjhbw** [comment] 2023-03-06 10:17
@gognjanovski I don't think that's related to this issue, because HTML images are treated very differently from image commands using `IMAGE` commands. The HTML is inserted as-is using the altChunk spec, which AFAIK only works in MS Word. 

If inserting 2 images works, but more than that gives you an error than this may be a limitation of MS Word instead.
