### ISSUE TITLE
Unreadable content when adding images to report 

### ISSUE THREAD

**Issue by sebastianplsim** [guigrpa/docx-templates#128] opened 2020-06-01 16:04 UTC
Hello -

I'm encountering a strange error when adding images to a report.

We're using base64 jpegs inside of loops.

This is a placeholder base64 jpg we're using:
```
{{IMAGE ({width: 13, height: 9.75, data: '/9j/4AAQSkZJRgABAQEAYABgAAD//gA7Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2NjIpLCBxdWFsaXR5ID0gNjUK/9sAQwALCAgKCAcLCgkKDQwLDREcEhEPDxEiGRoUHCkkKyooJCcnLTJANy0wPTAnJzhMOT1DRUhJSCs2T1VORlRAR0hF/9sAQwEMDQ0RDxEhEhIhRS4nLkVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVF/8AAEQgBHwDIAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A9ZoooqUBWs7CKye4eNpCZ5DI29icH29BVqiiqAKKKKACiiigCJx5p2H7vf3pl7dR2FnJPJwka5x6+gqxWF4tJOk7AQNzc/kaluyuNK7sZXhOybUr+4128+dy5SHPb1I/l+ddJdarb2pdMmWRBlkTnb9T0H41ynhjw3etZRST6heQQEEpGkuMgnggdh+efat6DwvaQupaa5mjBz5UkmUJ9SMc0o3sN7lGSzfxIhur4LbWaA7AvLOP7xJHSqkdn/YsMWoOqTWgyFimxvUZ4Iz3ro9RCyvFak7YgDJLjgbF7fiao6fZtqUg1LUfmXcfs0J+6i54JHcn/Ck0O5U/e6laTatd7RGsTfZoRzs46n3qKz/5Atj/ANchUeszDTmuYASILhWZB2DYORVi1QrpFmvpGKlbj6EDjPGeTVCUDNaD8VScZG71FUIpSrlCPUVCVwCKssDzUTCkBXce1RkVKwJqMikBE3AzSbQy/PT9uOtIwyPamIYIgSfSiq1zdiL5V60VSEez0UUUALQQD1pKWqEFFFFMAooooAK53xLIz+XGpyOc8d+1dA5wvHU8Cue1S5QX0Nv1Z3REAGScMCT9Pesqr0saU97nQRRrFCkajCooAFOJCgknAFLWTq92pBtQxCBd87A/dT0+p6fnWjdkQtSlLcteSukYIa7bapPaFerfic4+tbAXCKqjaqjAA7Cs/TYG3yXcqbJJsBU/uIOgrTYYXJrK9y9jm/FMMUlgFfs459MnH9assoSzt1HICcUajZi/vLeB+UJZmHsB/iRTYzu06A5zgEfkaFuHQqP6VSlzgYAx3q8w5qo4znPamIqNUT45qZ+pqFunIxQBA4wDUTCp35NMOMUgIiMCqU9wYsgmrrnC5FYl7KHkOT0poTIp5Fd8r1oqvAQ2760VaEe/UUUVIBRRRVALRRVe5voLSJ3lfhMbgvJGaaBJt2RYpaajiRFdc4YZGRilpiK15cCBN3GQO/b3rL0S2+0XE+oygHexWL2A4z/n39azNYvzdX8lpGchnCbieEHc/r+lasWvadC8en6fuu5I1wEgG4KB6t0rFO8rvoatWVjTvbtbK0kncZ2jgDufSsPTbae/CySrthZvMkZvvSt2wP7o4x9KbHLcavq032pAltZgDys5zIeeexwP5iujiXEYqn7zJ+FDVjC0xzk47VJI20VUu7qKztzJLyzHaiDqzdgKTBFaSZUuLqccLbQ7cnux5/oPzrOs1ddItvM6sC34Ekj9DTJBLqtz/ZUbfuwfMu5V6EnqAf0H0rTv4khCRoAERcAegFJajMp85qlNkMoHRutXZKrSc4piKjjPFQSCrL4wTiqzsA6j+9SGQnnnHNMP6VK2N30qGd1hiLH8KAKN7cBfkU4PesK9BClh1rRkO9yT1NVplzxV2JKlou2PJPJoqVEK9uKKEI97ooopAQXdytrCWZlVjwu84UnsCaZp9215bCSRQj5IKg5HBIB/HFQ63Zm+0qaESOmVJOwDLY5xVHR5LaK6NvGTvYFg/ZiPlYfmtF9Q0NtZomlaJZFMijJUHkfhWdJZrBfO0UY2TofN3Hg8+nUnmobe6thrLhNxcRkSyg4ViGx09iWH4VU1zWja3CCEB43BDSI3IA6j2ySORSlJJXAv3utLplurOjSjcEL5Cjce3rU99qsNpHKrEiRUBAwcHPA5+tYFxrkUViXRcKIm2rI+7J4x39DnrVW5uY57BmuJBLe+agKochR8p49+2an2qa0Ki4uysT2mi2+tOY7piYE2s+w7fMY54z16gn8q6e10+y0q2KWdvHAgHOxcZ+p71zWiX2nSXJiaeNZzN5ogZ9pOcYIB4OOvHvW9e3IuLg2EbEHbvmcfwJ/ieadPSFxyfNIhRktLAzMMGZmnf8en6YFZlv4rK3yxzhfJY44/hqLxBfN9ifAI3EBQPSuWmx9mRjkP6CpbbehSjdanos2oKGIjBlcDJAOAo9Se1cw97c6rq3lW37y5HCkA7IV7n/PP51HYJqGr28NjbzLFEMmVsc49feux0rSbbSbbyrdeTyznqx9TTSchO0R2mabFplr5UZLMx3O56s3c1V1T/W/hWvWPqn+u/CtGrIhbmRIaqyZC5Bqw5weeKrydKQys49KilRdofuDUzHHFQsRjFSMgdgOTwMZNZF3cee+B90dKuahPtXy16nrWacKMnrVIRE/yg461FtPHrUvrnvTCwU0xDWxRSY560UwPdKQkKMkgD3qtqF9FpthPdznbHCpYmvLtT+I6yzkRJJL6AttH9aylKxcIc27sdZeXOpJqMih2uLYzKwKsU2Lknghhn0Iwc/pVK4aeyvYHssSKjSnYxKlw2W7dgx4+nvXDXXjnU5ZWZIoowTnAySP8/SmQa7qV2zGW4KbYSxKLg5zgD+tZSlI2lTppXdzrA13JLIUmjYyHGSBwRyMccAY4x35+t7+ww8TJd3qymfClguCOeD15OcfpXCHUr6e3uGQzQxrIXRozhm4AAJ647/iaWF9UvY7VfPnUqxMknmsAucYJJzxjPHrWVnu2RGMFHVHYzQRKUQqshVwPMcYIXAOfqSwzWjBo5Mge6kAPJZkX7x5/xri9QS6iizBLK+6MqZWcnA2/nnco565/Ksa2tfEF3B5sd7clPe4Yf1pQit7lUI817I9YGm6a+mfZbqGObaWKSOMFSfpz+tZ1vpb6dCUttVIZmBZpEDbu2OteeR22sRnNxf3KLnB/ft/jWtyllvaSed4W/eASEkqe+CfWtrNpFyjTi9jo9alkkijR5UYbjyowO1QxmFIAHYH/AGVGc/jVGG5ilso4irSRJnBJGQSSTn8asB4H+Xy2Rc8e3H/66cXYh26GvpFyLC8W4H3MhWUdlJGSfpXdo6uMqwYexrzAN9knSZG3xnp/hVG58aSaZdsjxSog+66HqO1WptPYTgpdT1+sfVeJ/wAKzPCfjCDXmFuzgzbNynoWA65FaWrH9/8AgK0vdXMbcrszHfg8VXk5zU7nDGoG70DK7DmqtxIIonbPI/nVp8A464rFv5Q9yVX7oH60gZTkYlix5JqLk5J61KRjimMOKokhZPU81E8fI9qmOAaaeOtAEbDPSilznmigD26WGO4ieKZFkjcYZWGQR71xmp/C7Q7qQz2yzWkgO4LE+VJ+hz+ldtSE1I9jxBdHjLZZRmrQ05UX92FDcYyOOOeauajcCxvpbcwSM6MRjFVvtl0+Nlpj/eauKV0z2aXK4iQws0oecGUA/MCeuOlaMdysqlI4otqjmMxjFZkkuoD7sMS/jVuOB3XzI/lJ5K57+lOnZ6M5q1JR1jsTyeTOm2eB4sg/NE5H6HI7+lOgtUjtHitJ8sRnZKuP1Hf8KfYRsxeS7GAo79Pp/KkYJEj3IRjK/CZIwK1cEjFVJR2MmU/ZL+FHcGGVCsi54Zs8H6ioAz21wZWYcKAQDhZEzwfrzmrOoxZtQzRlzGwckEf59aE02KWyhnjd/Idd3lMfueoFVfQyerIEeSCOS6jy0ck5jYKOBg4BrZVJhKQ+0xnawJ7AjPX61PpECzkWjKvksvIx1Fc3rchvdRuIrlh5NvL5aQq+0BQOpHck4+go33A3J9WsbWNxJNGjg8AHIJ+lUYtOtfE06WhuEjL5IkA3f4VN9ngttCt1mtoxM+cMVG4Jngnv0qLSLKGx1q2vI2VVTkgH1FNaMTO48MeAdN8MTi6hkluLvG3zJDgKD1wB/wDXrQ1Xm5P0FaFrex3EakEVm6q3+kv9B/KtehktzIkJz71ATnP1qWU85qAn5T6ZoKKtzMIYSwxnoKw265q3ezebMxz8i8CqbEZo2ERt3pn1pznjI/Km9uKYhm75iKjOSalbAHJGahOe1ADWyHAFFH8eaKAPcaSjNJmoGcl4xhX7TbS7RuZSCceh/wDr1zmMiup8YLmG2f0Yj8//ANVcqGxwa5K3xHq4V+4OKg06EeW+cZU9R60lOBrFOx2OKkrMluFLWwdE2KchvmzzVYZmW3Kx42khj2JxUxMnlkI5XPbtWVdaqdPtnlVVLJnOe5rpjPmR5lak6b12LdzdQaXm7nkKqflEYG7f7Ad6htvFVoHVZ9MWCzkbbvRslGPquOPwzVDTBZ6nYmbVZGMzncrJ/wAsx2wK1bGz0u2ZmdpbuRgdm4BQvHXHrV6I5y9Fi3vQ9rIHTghh0xUViI11q7nFlDI7ncCUyVPrWfLb3mn2ZuLG2luY5D9yMZ2+9Q+F9Rl/tme5vy8SRpsWFxtLE+3sKlczLdki7qgurhiwJkDNg/KeDWQd0Mw3OqlepZ+T+FdNqms24hO3kDsD/n9BXKyXERVpCzIp6AEf4ZrVLuYtnaaLqhIVd+cfXmtm4l852bPp/KvPNGvSl0oLNtPTPOfyruIX3Rk/j+lUSRTYB+vf8Ko3Umy1c9zwKs3sywJuY8Dt3NYU9w0xLZ4HQVSEQO2TgdutRnHakeT9/s6HHPvSkANnqaYhjdcY4qMqT0NPPU8008DnpQBGV4pMHNKTikBJzQAmMZJFFK2CMGigD2qkNFB6VmUYHiqPfpRb/nm4b+n9a4s9RivQtWg+0adcRDkshwPfqP1rz4EEA+lYVl1O7DS3RKppR1pIz1p7cGuax6MZDxnHesbWdJa8ibyuG9+lbgwaa+ORVRbTuhVEpqzOSmkNlbRxswLDoo/hqzpUnmSrI7/uxwzHofYe9a8un29wxaRAcc571lXFukNz5s02EiGVj4wB2H+PtmuiLTPLq03A6iXUo7WyKQ4j44VRjArnPs8Uha5ugGdscZ6Cs26nToJ2YkEE7upBGT/M1nT6g4/diQ9PWr20MC9rF3BH8sOAB1I6VhGWTULmONFY4/iWorgTzSKo6Me5xWnBaxWNrs8wiaTowGRVohl+G7Nuqkbso+Tz1A9u9d/p12s1i0qjjrx9K84W3nEIMik4HIDbq3fDepOIZrVgRu5XPYUwZq3szyHdIxNUlOVOKnujgHvVePlOfStOhIxlzJnjPQUrcf8A1qUcZz1NMLA5+tIBjYxmk7fNTm4HpTD70ANJGc03d1pxXPNNPrQA09c0UrelFAHpH9q3f/PX/wAdFB1a7H/LQH/gIqlmkJoshlh9Wuum5f8AvmuWlUxzyJ0wcitxulZOoxlZlkA4IwaxqxvE2oStIjRv1qQnIFV1bipg2VrjaPUiyZeBnHWmknd9aA1GeaLFcwwnAx2rmdZDSXEIK7g77jjvg4A/n+ddIxHNZt4nKtwAp6jqK0puzOfE6wOWNvHIitNJ5TrzsJx/npTU2M+20gaRyTzjNdlbaVbXvzS26n0JHNXE062tl8uFFjUcgjjJrZyPPUTjk8MX10h8yYR+2OlaFho0WlKZLh/Ml9O1dQoQDAyTjnFVLmHzFK7x6gEUuZ7D5UYMjNLKQ4yv51RMz2l0j4ACv64/TtWpKuzdg47cetc9q9wiKxA+boOvStY6kSOwnlEkSsO4yKjTJTiszTb37Tp8ZPXAGM1pwH5BWvQjqOPBqHGCc9zUpph4H1qQGN169KTrzSsCCCO9NbIpgNJPamkindTTWAoAaDjmijpRQB3DTKoywYf8BP8AhT0UyIGQEg1neQUdXaJSw6MAMj9KAZcYZlUZ6EmsPbeRryFybco6c1VmVXQ9GAo+zrtOXYnOcBjj+VV0eSZHDeYjAkKGJYEdqHUTQ1B3GJCB/ACPfP8AjUgh5+6BTN12sXmKsMkYGcjcM/oakaa6RNz28AGM5E/H6gVzWZ3qcO4q2+G6CpgIxjdCuR1PP+NVoL24lZjDaCYL1McyED9aka4nVS0tr5YHPzSL/Q0WK9pB9S6/2WVfniUAdBg1kahGqR5AHPTjpV4G625W2JU/7YrG1q6mARHjCHOACT/9aqitTGco2dmSW9z9mgOcnHNNtr2S5c7o9o9TWHJeOtztSUEE4Ge59qvaW0ysRPjDH5SDnitWjluWbue6EwEBCRgckdTVU3Ny0mPPPH3gQK03i8w4P0rPu7JiwSLqe+cYFJAUL+6iEW1CWfpjqf8A69cxqE7MpjePqM5I5Brf1L7NZALw7sODnnv3rnLjUSx2MoKZ4yBk/jW8EZSZoaDdAQCMkA7uK62D7gNcDYnbqERAwrOMcetd9bH92tWyEKT+dNPPFObg4FN7YpDGkVG/LcU8nPFMbrxTAQjFMOS3NPb2prGgBrDiijHODRQB3IT5RgqR3wTSrbjOflJ9m6UBjn+H8e9S5Y9MD0J6GuE6RvkKDkIMnqR/9cVG1sEJKIuTyelP3SEDaVx6n0pxLk9gc8YOM1IDYRIv+qjB7cDP9ae8c+PmiJz39KRZWQY2A/Wo3lmLYyRimAoMyAgZUdPmGaiLzfeWUeoATOf0oBKMGIYkc4z/AEoWYkZIbnjAagRBK8+Gyx/LFcpqgkn1FYwQCFJB645612UrS+Q5hAbI7VwmovMNUypw7DGc4H51pT3JYn/COowWRLsiRSDk9M9RxUca3ejJ5czefAWJEg6qT6+2cU838ukWxjkAL7sg9eO5qgniGWZtl7Gfs8nG7b0PrW9mRodYspEu3se49az724nklSO2wpfO5/Qf5NM025yXDsD5e0hvUetV9RvBp+XGWlk+WNRztHdvr2pKOo7kT6bYsV82UtJ/td/84qhe2tgp/wBWu7HBbPNVJtVa5BMpIcHOR2qmU+0fM1zjae/WrSIbDIXU7dQCMOOv1ru7c/uV+lec2zbtRi+Zm+ccmvRLY/ulBHarZKHv1NNpzcU1qQxpI54zTD09KcTxxTDxQAhNNbn60p4FNyCKAAnAopuKKAO4BZ1BJUezdakVnPHU989/0qt5652huemM9aekg5+cEdfpXAdBIS/YY44HSo1nYncD+RzTCVXpjPcn+lNEgZjkAgDByf6UATNJuXBYfTrSGUjB3ELn8KhLmNQQPlPQ9qRn5BZQu7/a5NMRMJCGJH169aYXbkAYwc9ePwqIO6ZPIHTC9qaXZwAG+XmgCRpfMzgnAGAo57VyOpxN9qB2sTnn2FdQ6iUYIGAc9PSs3UYsnzVXA6MueoqoOzEynbaNasY2nLyljv2M2fzrWltLLUbV4GRWQ/LkcflWZOrSxCG3jKIy4eTHIX0+pq3Z7o0G792i8KnoPU1cu41qc3PZS6Nc+V5m+FmwpPBHsa6izs7azsTdXBEkrjliOAPQe1ZHiCIzTWqDP7yQYPpzWzqUebRYkfYVUAE/yqm7olLUwtRsLO9+eMKpP8SjIrltV05LGF3L7nJwMVsOl3ZyO0AByeYs8fUVg63eSzSCOUbe5X+VawIkUdOGb+H/AHq9Ht/uLXnelLu1CL2Oa9Dt/wDVr9KqRCFkJH3QM5xzSNntT2OaYTSGMz60hpSaRqYDO+KjVCrMT3qQjim7uMHrQA360U7rRTA6w7SAdoIFNBAOSM9+OaYVU87sdqcwIBCjgfTmuA3JPM2lcEBh6Cl8qYqXKSOueMLgCoD0+XBbvupQQcDAJ/lQAvmHew2YUfxZzmkLByBkDjqwxSbw2STy3bNM81XICbNwoAeJCOeMA9utNkLiMEHnvkc0w4yTn5sdMnmmeY5JICtj+8KBEjS/uyq7SW46j/P+e1QNKMbGOEHJyBTiy/ecBVBzkCog4JKE/IfWmgG3FwIrT91EGP8ACoIFY8N9Osu2dcAnNadwFltwTgjlmA6nHNZflol3ggkFcqvr7/lWoF4/6Ze2bhvlhfc2R2//AF4qDV71/OYIyMpGcZxUVvcD7Q8IO0heg5PJ/wDrVG4DX3lI5xtBJPXOSKEBFHctcKchhxnLDP6jiuR1SYz3zgnhTjNd3GyjcBuOUDBifXOP5ViXWiRXeomVQApUMQO5rRSS1ZnJGXotrvnaZAdq8ZxXZwnEa/SqMVulqFQCQj0jAIFXY8p8p4I65p3uKxIRimE808nIpjcdqoBppp6U/PFI3tVCI81GDknIp7cD3pvU0gEJx3opGXIooA6dmLscYIx0xSABSApGf4uKj8wk7gcY7UgdzkcZriNiUOdu0kkHtmk8zc2FjIHcke1RKT97PPvSFiuSSDmkMn3H5uCQDjJpS6BQP5DBqsu/klge2O9LhxJkjgj3FMQ5ipHJI54x/wDqp3JwF3fL0LGo97RsSwB57jpStO6Z8mNWbO0gKePzoAV3K5yAPwqBY97fd/8Ar04NlcNlcnJ74/CnOpSMbYwzHpkHn8BSAqT2ib1MYKMrcbW6evtVSLRUnX97NOVjwV+bp7cCtHe/k7XUKGJIOM4OP5U1BK8ZMc6FRzwh55+lUpPoxWM59Dt4W3wb4n7sjnP6mqn9kXcU0s0d4C8h5MidO3HP0rbuHOxf42I+/wAD9B/WoDdiRAFVfl4+RMn86alLuJoylsb5rl3e4jAZQu0Anp0/nV+1s1tEz5u9ycMxP6fSnFlY5Cn39RUIucyeSEYsvzFkHA6d6ptvcEjRWNh2AYHI45wagm2ebuXnd6UkUjF1c7AemGyeKWeAqPMdsk8DHFax2Je4gOf6VGTTsgDFNxVoQ0jimk88U8UwiqENJFM6H2NPPPSmGgB3BopnTvRQI30XuxwevBphb59uST274psbMgIDMAeCB3+tSRr1IGSehPauG5uQP5iEA5ZWI5GPlqcOmAARz19qCqls9vpTWT5e3J7UrgOZJI/3gUEE4Ucik3uGLuM5HJPrUbhvLYLIUBP1zTg5ZNpACjoWHWi4C4ZnDHII59KVAzO27IGPvE4pjFmYKAPXpz+dDMdpyCx6ZODigB0AVZ/3oJxk5AyfpRKAZPMPCscYJ5qJUZVGGwM9VOamDB1LSbBjg4XI6UAVrghtoBIAOcCppFW3TcH3MewNVoxvJOODxippjti3bACMZOe/pSAryT7yxJ2gAcnmm/u3RmL8/h1ps0TiUjcYwewHWiRMLwST7H2/Ki4hy7VG4tkA55pQrKWPDFjkHpgelLGhARQfrnvQ2WLAYB45GKpAOXfjeFGSMfNVaZnx87FgMHA4xVmON2Ug8jGTntVe5P3RtPXgDvWkbokAMItIfUUgbgg9uKAe3WtkIcKY2OaccjmmnmtESMzTHHPBqXAxzUZxnA60CEHSijp0ooA3wrEgsVIx35oIZgBu6Hjmq+4x4B5z3xUwVdocjnpzXAbiZYDAkzjgcdKY7uSVVi2e4HNLLcKjfLgLjkCmbipR+SH4AxTEN8t0I3MWwfxqaIjaST3wFxz+dIZI2Xrh/fpUIDOTuJXHrQBYdkQ5BJz+YqAq+7jkHv6UrHC4/iHOSafCjSJuxgjsTSGI5YxqWYiP0HWo5poAPmLLxgMSKn4lKeaBGAME4wTUN1HEZVWCTcByeP0oAgjbDIwkA5zmpXkMsZQsTjnPrSwrG7kNz2GRnmmurrnYjHbgcCkIhChCd2ST+f40r42jbwT19qgJEinch9OOM0AtjaACBj5u4NO3URZWMFsEjHrTiExsQ9/Wo1XbjnJzS4AZlwA2KnqAkkLJgpJuJ7E1VZZi5TnPGB1qYyRoGw3I7ZqW3ClixHykZB9a2ixFco0agP1NJnDAd/ep73aGRu1QnG/JH0rdaMTBs9OlGePakyCMmmkc8dK0IBueKbtAOadikbB6UAMPU0UjHtRQBrFkdSc9OuBR5oRcKDnvUtwI4UIhcM3cEUyCI3CFpGEZ9hXBY2GfaS4ww+X0pwmkKERowVuMjirUkHkQoD8yj+IYyaiiaJjtViv94tjmmMg8k7SGV1JHUmno0UETbs7hwAP61Z2WzKMzsGH97pWXfwXckiNblPKB+f1xQItEieQeYeoGSOKkbdvI2kqvp0qC2gUgMrqN3HzmpYgzuwLAcdOxosAvmAuBK7OCfug81Vmwru0YCk9cYzirJUqpVEDv1+UdKqiQFiJID9M4pAPhVQjM+ATx0yai3LvYRvkZ9MZq2qIE4VST1Uv0qtcNAHUqrK/QgDgUnsGoo2hTh+fQ1HtVV3bsL654FNMgClieOgFMJypDsCpH60JMkso4I+XkevY0m7CnJ5HWoINpCqrADuxPSlnTerqr7wDge4oaYwaSJGDEqAeM1OuDhk+529hUSlVhSCKNUjB7Dqf60FmU8kkfpV3XQGOumVtoXqOSag3/AHuCO9MkmLKyqpB65pIc7ASdx7muhO5I9jwPekLetBBJ+lBrUgQAjNJnApSeaYxyaAA80Uh5ooA2o0BYyM21x14yaVpVQEEknOagDFOQcH1qUJ5yli2WY45rhNRglLqRuY5OeKmiikVRuGxfVutNOy1YCVC3PY02R1lOSzYHRTQMHCCQhWVw3GSOlWvsQ8rCHLHt2rOZ8DOPyqzDJOynL8DiiwBJC9uFaQYA6gDAqPI2NtK7QO9TXEwkQRjcdo6t3qnyvRRg8UroGTxbdhYuy85wKqXaysTJGrBQBjI5qdXURfKhLn1PSlJIT58juRmmBRDs7jAcnjk8CrBdlx8vbtU0kbKgc9COAKryTFkAJ2sOlSJspokwVmnUcnsO1Ti381N2foCKkt5sMOd3ODkVNf3ZQqsfynvxV6sRAiIqc9QeeccVCkwE+FXCnv7UpcqVL8g9R2NMWENulQ4BPT0ppNrUCWOZ5Gb5cKDgetPI3Z6+lNDjCqOuKjeVPm3Z+X0oSETJGGTEQwcYyTVaNfLHl9lqVJ8rtjO3PPTrUcIHPPNbx2QmPz2pDyKXtTa1JEzTSMj3pxphPOKACikzg0UAf//Z'
, extension: '.jpeg'})}}
```

* **Outside of loop - no problems cat loads** ✅
* **Inside of loop**:
![image](https://user-images.githubusercontent.com/25442565/83428465-56cbcd00-a42a-11ea-8fc0-38f857eebdff.png)

**Comment by sebastianplsim** [comment] 2020-06-01 16:25
So I managed to fix this issue by removing all existing images from the template and adding them back in 🤷‍♂️

Happy to close this issue if the issue is unique to the template I'm working with...

**Comment by jjhbw** [comment] 2020-06-03 18:54
Thanks for your report!

Sounds strange... Let's not close it yet. I'll see if I can replicate this first. 

Good to hear that you were able to circumvent the problem for now.

**Comment by jjhbw** [comment] 2020-06-06 12:43
Hmmm I couldn't reproduce this i'm afraid (see 674dbf2d4971d329a033ce71be52c4ca43b15ec4).

My money is on there being some weird corruption in your template, or some kind of OpenXML spec weirdness that docx-templates is not aware of...

I'll close this issue for now, but please reopen if you notice something similar again or have any new info!

**Closed by jjhbw** 2020-06-06 12:43 UTC
