### ISSUE TITLE
<img src='url' /> in HTML is blank

### ISSUE THREAD

**Issue by llaidie** [guigrpa/docx-templates#156] opened 2020-10-15 20:08 UTC
hello, i have this html code injected on my document but the image is blank.

+++ HTML`<!DOCTYPE html><html><head> <metacharset="UTF-8"></head><body><p><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Google_Images_2015_logo.svg/langfr-552px-Google_Images_2015_logo.svg.png" alt="" width="552" height="190" /></p></body></html>`+++

can you please send me an example to insert image from url and image from url in HTML tags

Kind Regards,

Ludo

**Comment by jjhbw** [comment] 2020-10-15 20:19
I doubt that this is possible. This would require your document reader (e.g. MS Word) to make a http call to get the linked image when the doc is opened. The security implications of this are huge.

Are you sure this should be possible? I dont know enough about the docx spec to definitively say its impossible.

**Comment by llaidie** [comment] 2020-10-16 05:16
@jjhbw 
The html code is pushed  only one time when the docx document is created. Not each time you open the document

**Comment by vdechef** [comment] 2020-10-16 06:58
Actually, it works but the image will only be loaded when you open the document in "modification mode".  
Docx-templates will insert the html file in the docx archive when building the document, and Word will convert this html file when the document is opened for the first time : if modifications are not allowed for the document, Word won't make http call to resolve the URL, but if modification are allowed it will resolve the URL and insert the image in the html content before converting the htlm to open-xml format.

**Comment by jjhbw** [comment] 2020-10-16 07:21
Wow, the docx spec keeps amazing me (not always in a good way, haha). Never expected this. Thanks for pitching in @vdechef !

@llaidie i did not mean the HTML _code_ but the image that the HTML `img` tag refers to. Also; why the thumbs down? I'm just trying to help. Sorry if my remark came off as dismissive. Its just that this use case is very unexpected to me.

Your example throws a syntax error when I copy it directly, so I had to format it a bit (see below). Also note that you need to provide the HTML code as a string literal (note the string literal backticks).

I could not reproduce your issue using the below command. The `<img>` tag seems to render just fine in my Word 2016 install.

```
+++HTML
`
<!DOCTYPE html>
<html>
<head>
    <metacharset="UTF-8">
</head>
<body>
    <p>
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Google_Images_2015_logo.svg/langfr-552px-Google_Images_2015_logo.svg.png"
            alt="" width="552" height="190" />
    </p>
</body>
</html>
`
+++
```

I'll close this issue now. Feel free to reopen if this doesn't fix it.

**Closed by jjhbw** 2020-10-16 07:21 UTC

**Comment by llaidie** [comment] 2020-10-16 10:07
Hello,

Thanks for your reply. Finally, I decided to push a base64 image and everything is fine.

Thank you guys

**Comment by loizos01** [comment] 2023-11-10 15:34
Hello I have a similar issue, I create and inject the image like this. I tried with base64 and with the url it self but nothing works.       
```
const dataUrl = await imageToBase64(`http://docxtemplater.com/puffin.png`);
questionHtml +=`<p><img  style="height:100px" src="data:image/png;base64, ` + dataUrl + `" alt="test"/></p>`; 
```

```

The following is in a for loop but ignore that, the rest of the information is displayed only the , <img> element is not shown
``+++HTML `
<meta charset="UTF-8">
<style>
table {
table-layout: fixed;
border-collapse: collapse;
margin: 0 auto;
width: 17cm;
}
th {
border: 1px solid #585858;
padding: 2px 4px;
}
td {
padding: 0 4px;
border: 1px solid #585858;
}
</style>
<body>
 ${questionsListTableHtml[$question]}
</body>
`+++
```
